ALTER TABLE slides ADD COLUMN IF NOT EXISTS cloud_upload_status TEXT DEFAULT NULL;
ALTER TABLE slides ADD COLUMN IF NOT EXISTS cloud_upload_mode TEXT DEFAULT NULL;
ALTER TABLE slides ADD COLUMN IF NOT EXISTS cloud_upload_at TIMESTAMPTZ DEFAULT NULL;
