#!/usr/bin/env node

/**
 * SuperNavi Edge - Setup Wizard
 *
 * Auto-detects MOTIC scanner directories, saves config, generates docker-compose.override.yml.
 * Runs on the HOST (not inside Docker) — uses Node.js 20+ stdlib only.
 *
 * Usage:
 *   node setup.js              # Auto-detect + interactive wizard
 *   node setup.js --auto       # Auto-detect only (headless/CI)
 *   node setup.js --dir /path  # Skip detection, use given path
 *   node setup.js --reset      # Remove config + override
 */

import { createInterface } from 'node:readline/promises';
import { stdin, stdout, argv, exit } from 'node:process';
import { access, rm, mkdir } from 'node:fs/promises';
import { constants } from 'node:fs';
import { join, resolve } from 'node:path';

import { getBestCandidate, autoDetectScannerDirs } from './api/src/lib/motic-detect.js';
import {
  getDefaults,
  validateConfig,
  saveConfig,
  getConfigPath,
} from './api/src/lib/edge-config.js';
import { writeFile } from 'node:fs/promises';

// ============================================================================
// CLI argument parsing
// ============================================================================

const args = argv.slice(2);
const flagAuto = args.includes('--auto');
const flagReset = args.includes('--reset');
const flagDirIdx = args.indexOf('--dir');
const flagDir = flagDirIdx !== -1 ? args[flagDirIdx + 1] : null;

// ============================================================================
// Helpers
// ============================================================================

function log(msg) { console.log(`[setup] ${msg}`); }
function warn(msg) { console.warn(`[setup] ⚠  ${msg}`); }
function ok(msg) { console.log(`[setup] ✓  ${msg}`); }

async function dirExists(p) {
  try {
    await access(p, constants.R_OK);
    return true;
  } catch {
    return false;
  }
}

function generateOverride(slidesDirHost) {
  return `# Generated by setup.js — do not edit manually
services:
  api:
    volumes:
      - ${slidesDirHost}:/data/inbox
      - ./config:/config
      - ./data/raw:/data/raw
      - ./data/derived:/data/derived
      - ./db/migrations:/app/db/migrations:ro
  processor:
    volumes:
      - ./data/raw:/data/raw:ro
      - ./data/derived:/data/derived
      - ./config:/config:ro
`;
}

// ============================================================================
// Reset
// ============================================================================

async function handleReset() {
  const configPath = getConfigPath({ host: true });
  const overridePath = join(resolve('.'), 'docker-compose.override.yml');

  let removed = false;
  if (await dirExists(configPath)) {
    await rm(configPath);
    ok(`Removed ${configPath}`);
    removed = true;
  }
  if (await dirExists(overridePath)) {
    await rm(overridePath);
    ok(`Removed ${overridePath}`);
    removed = true;
  }

  if (!removed) {
    log('Nothing to reset.');
  }
  exit(0);
}

// ============================================================================
// Interactive wizard
// ============================================================================

async function runWizard(rl, initialPath) {
  const config = getDefaults();

  // Step 1: slides directory
  let slidesDir = initialPath;
  if (!slidesDir) {
    slidesDir = await rl.question('\nPath to scanner output folder: ');
    slidesDir = slidesDir.trim();
  }

  if (!slidesDir) {
    warn('No path provided. Aborting.');
    exit(1);
  }

  slidesDir = resolve(slidesDir);

  if (!(await dirExists(slidesDir))) {
    warn(`Directory not found: ${slidesDir}`);
    const create = await rl.question('Create it? [y/N] ');
    if (create.toLowerCase() === 'y') {
      await mkdir(slidesDir, { recursive: true });
      ok(`Created ${slidesDir}`);
    } else {
      exit(1);
    }
  }

  config.slidesDirHost = slidesDir;
  config.source = 'wizard-cli';

  // Step 2: stableSeconds
  const stableInput = await rl.question(`\nFile stability wait (seconds) [${config.stableSeconds}]: `);
  if (stableInput.trim()) {
    const val = parseInt(stableInput.trim(), 10);
    if (val >= 1 && val <= 300) {
      config.stableSeconds = val;
    } else {
      warn('Invalid value, using default.');
    }
  }

  // Step 3: scanner type
  const scannerInput = await rl.question(`\nScanner type [${config.scanner.type}]: `);
  if (scannerInput.trim()) {
    config.scanner.type = scannerInput.trim().toLowerCase();
  }

  return config;
}

// ============================================================================
// Main
// ============================================================================

async function main() {
  console.log('\n╔══════════════════════════════════════╗');
  console.log('║   SuperNavi Edge — Setup Wizard      ║');
  console.log('╚══════════════════════════════════════╝\n');

  if (flagReset) {
    await handleReset();
    return;
  }

  let config;

  // --dir: skip detection, use provided path
  if (flagDir) {
    const dir = resolve(flagDir);
    if (!(await dirExists(dir))) {
      warn(`Directory not found: ${dir}`);
      await mkdir(dir, { recursive: true });
      ok(`Created ${dir}`);
    }

    config = getDefaults();
    config.slidesDirHost = dir;
    config.source = 'cli-flag';
    log(`Using provided directory: ${dir}`);
  } else {
    // Auto-detect
    log('Scanning for scanner directories...');
    const results = await autoDetectScannerDirs();

    if (results.length > 0) {
      console.log('\nDetected scanner directories:');
      for (const r of results) {
        const marker = r === results[0] ? ' ← best' : '';
        console.log(`  ${r.candidate.path} (${r.candidate.scannerType}, score: ${r.finalScore}, slides: ${r.slideCount})${marker}`);
      }

      const best = results[0];

      if (flagAuto) {
        // --auto: accept best candidate automatically
        if (best.finalScore >= 50) {
          config = getDefaults();
          config.slidesDirHost = best.candidate.path;
          config.scanner.type = best.candidate.scannerType;
          config.scanner.model = best.candidate.model;
          config.source = 'auto-detect';
          ok(`Auto-selected: ${best.candidate.path} (${best.candidate.scannerType})`);
        } else {
          warn('No candidate scored >= 50. Run without --auto for interactive setup.');
          exit(1);
        }
      } else {
        // Interactive: ask to confirm best candidate
        const rl = createInterface({ input: stdin, output: stdout });
        try {
          const answer = await rl.question(`\nUse ${best.candidate.path}? [Y/n] `);
          if (answer.trim().toLowerCase() !== 'n') {
            config = getDefaults();
            config.slidesDirHost = best.candidate.path;
            config.scanner.type = best.candidate.scannerType;
            config.scanner.model = best.candidate.model;
            config.source = 'auto-detect';
            ok(`Selected: ${best.candidate.path}`);

            // Ask stableSeconds
            const stableInput = await rl.question(`\nFile stability wait (seconds) [${config.stableSeconds}]: `);
            if (stableInput.trim()) {
              const val = parseInt(stableInput.trim(), 10);
              if (val >= 1 && val <= 300) config.stableSeconds = val;
            }
          } else {
            config = await runWizard(rl, null);
          }
        } finally {
          rl.close();
        }
      }
    } else {
      log('No scanner directories found.');

      if (flagAuto) {
        warn('Auto-detect failed. Run without --auto for interactive setup.');
        exit(1);
      }

      const rl = createInterface({ input: stdin, output: stdout });
      try {
        config = await runWizard(rl, null);
      } finally {
        rl.close();
      }
    }
  }

  // Validate
  const { valid, errors } = validateConfig(config);
  if (!valid) {
    warn('Config validation failed:');
    for (const e of errors) console.error(`  - ${e}`);
    exit(1);
  }

  // Save config
  const configPath = getConfigPath({ host: true });
  await saveConfig(config, { path: configPath });
  ok(`Config saved: ${configPath}`);

  // Generate docker-compose.override.yml
  const overridePath = join(resolve('.'), 'docker-compose.override.yml');
  const overrideContent = generateOverride(config.slidesDirHost);
  await writeFile(overridePath, overrideContent, 'utf8');
  ok(`Docker override saved: ${overridePath}`);

  // Summary
  console.log('\n┌─────────────────────────────────────┐');
  console.log('│         Configuration Summary        │');
  console.log('├─────────────────────────────────────┤');
  console.log(`│  Scanner:     ${config.scanner.type.padEnd(21)}│`);
  console.log(`│  Slides dir:  ${config.slidesDirHost.substring(0, 21).padEnd(21)}│`);
  console.log(`│  Stable wait: ${(config.stableSeconds + 's').padEnd(21)}│`);
  console.log(`│  Source:      ${config.source.padEnd(21)}│`);
  console.log('└─────────────────────────────────────┘');

  console.log('\nNext steps:');
  console.log('  docker compose up -d --build');
  console.log('');
}

main().catch(err => {
  console.error('[setup] Fatal error:', err.message);
  exit(1);
});
